version: '3.8'

services:
  backend:
    image: aashinak/nuvellaserver:latest
    container_name: nuvellaServer
    restart: always
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - nuvella-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nuvella-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - nuvella-network

networks:
  nuvella-network:
    driver: bridge
