version: '3.8'

services:
  backend:
    image: aashinak/nuvellaserver:latest
    container_name: nuvellaServer
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - /home/ubuntu/.env
    depends_on:
      - redis
    networks:
      - nuvella-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nuvella-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/nuvellapi.aashin.xyz/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/nuvellapi.aashin.xyz/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - nuvella-network

networks:
  nuvella-network:
    driver: bridge
