import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from "@/components/user/homepage/clientProvider";
import TopSection from "@/components/user/homepage/topSection";
import Navbar from "@/components/user/homepage/navbar";
import { ScrollArea } from "@/components/ui/scroll-area";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nuvella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#ffffff] overflow-x-hidden`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
