name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove existing containers
        run: |
          docker-compose down

      - name: Pull the latest Docker image
        run: |
          docker-compose pull

      - name: Start containers
        run: |
          docker-compose up -d
